name: education_app
description: "The most effective way to connect teachers with their students, fostering collaboration, learning, and growth."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  build_runner: ^2.4.8
  json_serializable: ^6.8.0 #Don't forget _ while naming 'solved_problems.g.dart'
  json_annotation: ^4.9.0
  persistent_bottom_nav_bar_v2: ^4.2.8
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  firebase_app_check: ^0.3.1+4
  logger: ^2.5.0
  flutter_svg: ^2.0.9
  google_sign_in: ^6.2.1
  percent_indicator: ^4.2.3
  youtube_player_flutter: ^8.1.2
  flutter_native_splash: ^2.3.10
  intl: ^0.19.0
  audioplayers: ^5.2.1
  awesome_dialog: ^3.2.0
  flutter_bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  bloc: ^8.1.2
  meta: ^1.10.0
  shared_preferences: ^2.3.4
  flutter_screenutil: ^5.9.0
  flutter_flavor: ^3.1.3
  path: ^1.8.3
  image_picker: ^1.0.7
  firebase_storage: ^12.0.1
  url_launcher: ^6.2.5
  get_it: ^7.6.7
  dartz: ^0.10.1
  flutter_secure_storage: ^9.2.2
  cached_network_image: ^3.3.1
  flutter_local_notifications: ^17.1.2
  win32: ^5.5.0
  flutter_plugin_android_lifecycle: ^2.0.17
  add_to_cart_animation: ^2.0.4
  sentry_flutter: ^8.11.0
  permission_handler: ^11.3.1
  package_info_plus: ^8.1.2

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  change_app_package_name: ^1.1.0
  # analyzer: ^6.4.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  remove_alpha_ios: true

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  color: "#42a5f5"
  image: assets/splash.png
  android_gravity: fill

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
